[package]
name = "auxmos"
version = "0.2.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auxcleanup_gas_deletion", "logging"]
logging = ["simple-logging", "log", "log-panics"]
auxcleanup_gas_deletion = ["auxcleanup"]
equalization = []
monstermos = ["equalization"]
putnamos = ["equalization"]
katmos = ["equalization"]
reaction_hooks = []
plasma_fire_hook = ["reaction_hooks"]
trit_fire_hook = ["reaction_hooks"]
fusion_hook = ["reaction_hooks"]
generic_fire_hook = ["reaction_hooks"]
all_reaction_hooks = ["fusion_hook", "trit_fire_hook", "plasma_fire_hook", "generic_fire_hook"]
explosive_decompression = ["monstermos"]
putnamos_decompression = ["putnamos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools"}
auxcallback = { git = "https://github.com/Putnam3145/auxcallback" }
auxcleanup = { git = "https://github.com/Putnam3145/auxcleanup", optional = true}
itertools = "0.10.3"
rayon = "1.5.1"
float-ord = "0.3.2"
crossbeam = "0.8.1"
flume = "0.10.9"
parking_lot = "0.11.2"
fxhash = "0.2.1"
nonmax = "0.5.0"
indexmap = { version = "1.7.0", features = ["rayon"] }
ahash = "0.7.6"
simple-logging = { version = "2.0.2", optional = true }
log = { version = "0.4.14", optional = true }
log-panics = { version = "2.0.0", features = ["with-backtrace"], optional = true }

[build-dependencies]
vergen = { version = "6", default-features = false, features = ["git"] }
anyhow = "1.0.52"

[dependencies.dashmap]
version = "5.0.0"
features = ["raw-api"]

[dependencies.tinyvec]
version = "1.5.1"
features = ["rustc_1_55", "alloc"]

[profile.release]
lto = 'thin'
debug = true
panic = 'abort'
